-- -------------------------------------------------------------
--  016 – číselník jazyků
-- -------------------------------------------------------------
--
-- Jazyk knihy byl dosud volný text, do kterého šlo napsat cokoli („CZ“,
-- „čeština“, „cz “). Číselník drží všechny platné kódy ISO 639-1 – dvoupísmenné
-- kódy pokrývají všechny jazyky, ve kterých reálně vycházejí knihy, a stejné
-- kódy už v books.language jsou. ISO 639-3 (tisíce jazyků včetně vymřelých)
-- by výběr v editaci jen zahltil.
--
-- name_cs je český název tak, jak se píše v textu (malým písmenem),
-- name_native název v jazyce samotném – podle něj jazyk najde i ten, kdo
-- neví, jak se česky jmenuje.
--
-- books.language na číselník cizím klíčem neukazuje: v SQLite by to znamenalo
-- přestavbu celé tabulky books (viz 002). Kód hlídá API při zápisu knihy.

CREATE TABLE languages (
  code        TEXT PRIMARY KEY,   -- ISO 639-1, malými písmeny
  name_cs     TEXT NOT NULL,
  name_native TEXT NOT NULL
);

INSERT INTO languages (code, name_cs, name_native) VALUES
  ('aa', 'afarština', 'Afaraf'),
  ('ab', 'abcházština', 'аԥсуа бызшәа'),
  ('ae', 'avestánština', 'avesta'),
  ('af', 'afrikánština', 'Afrikaans'),
  ('ak', 'akanština', 'Akan'),
  ('am', 'amharština', 'አማርኛ'),
  ('an', 'aragonština', 'aragonés'),
  ('ar', 'arabština', 'العربية'),
  ('as', 'ásámština', 'অসমীয়া'),
  ('av', 'avarština', 'авар мацӀ'),
  ('ay', 'ajmarština', 'aymar aru'),
  ('az', 'ázerbájdžánština', 'azərbaycan dili'),
  ('ba', 'baškirština', 'башҡорт теле'),
  ('be', 'běloruština', 'беларуская мова'),
  ('bg', 'bulharština', 'български език'),
  ('bi', 'bislamština', 'Bislama'),
  ('bm', 'bambarština', 'bamanankan'),
  ('bn', 'bengálština', 'বাংলা'),
  ('bo', 'tibetština', 'བོད་ཡིག'),
  ('br', 'bretonština', 'brezhoneg'),
  ('bs', 'bosenština', 'bosanski jezik'),
  ('ca', 'katalánština', 'català'),
  ('ce', 'čečenština', 'нохчийн мотт'),
  ('ch', 'čamoro', 'Chamoru'),
  ('co', 'korsičtina', 'corsu'),
  ('cr', 'kríjština', 'ᓀᐦᐃᔭᐍᐏᐣ'),
  ('cs', 'čeština', 'čeština'),
  ('cu', 'staroslověnština', 'ѩзыкъ словѣньскъ'),
  ('cv', 'čuvaština', 'чӑваш чӗлхи'),
  ('cy', 'velština', 'Cymraeg'),
  ('da', 'dánština', 'dansk'),
  ('de', 'němčina', 'Deutsch'),
  ('dv', 'maledivština', 'ދިވެހި'),
  ('dz', 'dzongkha', 'རྫོང་ཁ'),
  ('ee', 'eweština', 'Eʋegbe'),
  ('el', 'řečtina', 'ελληνικά'),
  ('en', 'angličtina', 'English'),
  ('eo', 'esperanto', 'Esperanto'),
  ('es', 'španělština', 'español'),
  ('et', 'estonština', 'eesti keel'),
  ('eu', 'baskičtina', 'euskara'),
  ('fa', 'perština', 'فارسی'),
  ('ff', 'fulbština', 'Fulfulde'),
  ('fi', 'finština', 'suomi'),
  ('fj', 'fidžijština', 'vosa Vakaviti'),
  ('fo', 'faerština', 'føroyskt'),
  ('fr', 'francouzština', 'français'),
  ('fy', 'západofríština', 'Frysk'),
  ('ga', 'irština', 'Gaeilge'),
  ('gd', 'skotská gaelština', 'Gàidhlig'),
  ('gl', 'galicijština', 'galego'),
  ('gn', 'guaraní', 'Avañe''ẽ'),
  ('gu', 'gudžarátština', 'ગુજરાતી'),
  ('gv', 'manština', 'Gaelg'),
  ('ha', 'hauština', 'Hausa'),
  ('he', 'hebrejština', 'עברית'),
  ('hi', 'hindština', 'हिन्दी'),
  ('ho', 'hiri motu', 'Hiri Motu'),
  ('hr', 'chorvatština', 'hrvatski jezik'),
  ('ht', 'haitská kreolština', 'Kreyòl ayisyen'),
  ('hu', 'maďarština', 'magyar'),
  ('hy', 'arménština', 'Հայերեն'),
  ('hz', 'hererština', 'Otjiherero'),
  ('ia', 'interlingua', 'Interlingua'),
  ('id', 'indonéština', 'Bahasa Indonesia'),
  ('ie', 'interlingue', 'Interlingue'),
  ('ig', 'igboština', 'Asụsụ Igbo'),
  ('ii', 'sečuánská iština', 'ꆈꌠ꒿ Nuosuhxop'),
  ('ik', 'inupiaq', 'Iñupiaq'),
  ('io', 'ido', 'Ido'),
  ('is', 'islandština', 'íslenska'),
  ('it', 'italština', 'italiano'),
  ('iu', 'inuktitut', 'ᐃᓄᒃᑎᑐᑦ'),
  ('ja', 'japonština', '日本語'),
  ('jv', 'javánština', 'basa Jawa'),
  ('ka', 'gruzínština', 'ქართული'),
  ('kg', 'konžština', 'Kikongo'),
  ('ki', 'kikujština', 'Gĩkũyũ'),
  ('kj', 'kuanyama', 'Kuanyama'),
  ('kk', 'kazaština', 'қазақ тілі'),
  ('kl', 'grónština', 'kalaallisut'),
  ('km', 'khmerština', 'ខ្មែរ'),
  ('kn', 'kannadština', 'ಕನ್ನಡ'),
  ('ko', 'korejština', '한국어'),
  ('kr', 'kanurijština', 'Kanuri'),
  ('ks', 'kašmírština', 'कश्मीरी'),
  ('ku', 'kurdština', 'Kurdî'),
  ('kv', 'komijština', 'коми кыв'),
  ('kw', 'kornština', 'Kernewek'),
  ('ky', 'kyrgyzština', 'кыргыз тили'),
  ('la', 'latina', 'latine'),
  ('lb', 'lucemburština', 'Lëtzebuergesch'),
  ('lg', 'gandština', 'Luganda'),
  ('li', 'limburština', 'Limburgs'),
  ('ln', 'lingalština', 'Lingála'),
  ('lo', 'laoština', 'ພາສາລາວ'),
  ('lt', 'litevština', 'lietuvių kalba'),
  ('lu', 'lubština (Katanga)', 'Kiluba'),
  ('lv', 'lotyština', 'latviešu valoda'),
  ('mg', 'malgaština', 'fiteny malagasy'),
  ('mh', 'maršálština', 'Kajin M̧ajeļ'),
  ('mi', 'maorština', 'te reo Māori'),
  ('mk', 'makedonština', 'македонски јазик'),
  ('ml', 'malajálamština', 'മലയാളം'),
  ('mn', 'mongolština', 'монгол хэл'),
  ('mr', 'maráthština', 'मराठी'),
  ('ms', 'malajština', 'Bahasa Melayu'),
  ('mt', 'maltština', 'Malti'),
  ('my', 'barmština', 'ဗမာစာ'),
  ('na', 'naurština', 'Dorerin Naoero'),
  ('nb', 'norština (bokmål)', 'norsk bokmål'),
  ('nd', 'severní ndebelština', 'isiNdebele'),
  ('ne', 'nepálština', 'नेपाली'),
  ('ng', 'ndonga', 'Owambo'),
  ('nl', 'nizozemština', 'Nederlands'),
  ('nn', 'norština (nynorsk)', 'norsk nynorsk'),
  ('no', 'norština', 'norsk'),
  ('nr', 'jižní ndebelština', 'isiNdebele'),
  ('nv', 'navažština', 'Diné bizaad'),
  ('ny', 'čičevština', 'chiCheŵa'),
  ('oc', 'okcitánština', 'occitan'),
  ('oj', 'odžibvejština', 'ᐊᓂᔑᓈᐯᒧᐎᓐ'),
  ('om', 'oromština', 'Afaan Oromoo'),
  ('or', 'urijština', 'ଓଡ଼ିଆ'),
  ('os', 'osetština', 'ирон æвзаг'),
  ('pa', 'paňdžábština', 'ਪੰਜਾਬੀ'),
  ('pi', 'páli', 'पाऴि'),
  ('pl', 'polština', 'polski'),
  ('ps', 'paštština', 'پښتو'),
  ('pt', 'portugalština', 'português'),
  ('qu', 'kečuánština', 'Runa Simi'),
  ('rm', 'rétorománština', 'rumantsch grischun'),
  ('rn', 'kirundština', 'Ikirundi'),
  ('ro', 'rumunština', 'română'),
  ('ru', 'ruština', 'русский'),
  ('rw', 'kiňarwandština', 'Ikinyarwanda'),
  ('sa', 'sanskrt', 'संस्कृतम्'),
  ('sc', 'sardinština', 'sardu'),
  ('sd', 'sindhština', 'सिन्धी'),
  ('se', 'severní sámština', 'davvisámegiella'),
  ('sg', 'sangština', 'yângâ tî sängö'),
  ('si', 'sinhálština', 'සිංහල'),
  ('sk', 'slovenština', 'slovenčina'),
  ('sl', 'slovinština', 'slovenščina'),
  ('sm', 'samojština', 'gagana fa''a Samoa'),
  ('sn', 'šonština', 'chiShona'),
  ('so', 'somálština', 'Soomaaliga'),
  ('sq', 'albánština', 'shqip'),
  ('sr', 'srbština', 'српски језик'),
  ('ss', 'svazijština', 'SiSwati'),
  ('st', 'sotština (jižní)', 'Sesotho'),
  ('su', 'sundština', 'Basa Sunda'),
  ('sv', 'švédština', 'svenska'),
  ('sw', 'svahilština', 'Kiswahili'),
  ('ta', 'tamilština', 'தமிழ்'),
  ('te', 'telugština', 'తెలుగు'),
  ('tg', 'tádžičtina', 'тоҷикӣ'),
  ('th', 'thajština', 'ไทย'),
  ('ti', 'tigrinijština', 'ትግርኛ'),
  ('tk', 'turkmenština', 'Türkmençe'),
  ('tl', 'tagalština', 'Wikang Tagalog'),
  ('tn', 'setswanština', 'Setswana'),
  ('to', 'tonžština', 'faka Tonga'),
  ('tr', 'turečtina', 'Türkçe'),
  ('ts', 'tsonga', 'Xitsonga'),
  ('tt', 'tatarština', 'татар теле'),
  ('tw', 'twi', 'Twi'),
  ('ty', 'tahitština', 'Reo Tahiti'),
  ('ug', 'ujgurština', 'ئۇيغۇرچە'),
  ('uk', 'ukrajinština', 'українська'),
  ('ur', 'urdština', 'اردو'),
  ('uz', 'uzbečtina', 'Oʻzbek'),
  ('ve', 'vendština', 'Tshivenḓa'),
  ('vi', 'vietnamština', 'Tiếng Việt'),
  ('vo', 'volapük', 'Volapük'),
  ('wa', 'valonština', 'walon'),
  ('wo', 'wolofština', 'Wollof'),
  ('xh', 'xhoština', 'isiXhosa'),
  ('yi', 'jidiš', 'ייִדיש'),
  ('yo', 'jorubština', 'Yorùbá'),
  ('za', 'čuangština', 'Saɯ cueŋƅ'),
  ('zh', 'čínština', '中文'),
  ('zu', 'zuluština', 'isiZulu');

-- Starší hodnoty mohly přijít s velkými písmeny nebo mezerami (volné pole
-- v editaci); kód v číselníku je vždy malými písmeny.
UPDATE books SET language = lower(trim(language)) WHERE language <> lower(trim(language));
UPDATE books SET language = 'cs' WHERE language = '';
